travis:
  secure:
    BINSTAR_TOKEN: BRR66JUyWSDnmDS0TkXncn72XKNh5BodCJMc78TJc09mL9owAba8PtU50rA4twnGwwbELHE+4KG5zd1Ab/hy/fn2gyQoMYPKEBGBupsjtyAxXhNuAOWqXQoqJYFIA4sFC7RhbVRFLSpXu/HiigyBYU5USP/ogkrsKMfAsZEZFU0B67STaNBjBWI5T7xwbFmcjePQIvMpJ6Z5JLnmtSJ7KC2TsaPQh5SOwphlWzBzyDunSXLMmRK+jS+yrjIbs9eINTK9045AfdGlKSSMjXEc5LEbQfVml/sTqKWAINi4R1sYi87yp64ONpr1QM888EVPNxk65udGebCaMyb7HILH4yx8S0EkGV/EhJLkTh89DHjnhxJ5xD/hI2flBBTnVxZ9GGxhTEQEVtMIgDBZXAyjUlC5d7Wtye1IST6A3egg58AshtUCd390YPuUjNh7EozuX833Bmpr/46/dOxUApVvMI3n897ZlzGKke3TwxKJv8eSdDXU7gfWZL2DEkV4pE1UzX85wL+mWOOmCWHw2y6mw3WUF81dQpvTiHIKBzE9oJjBbxFzkYQjtiOHr3Gk7Cqqrbxm9tb27poWJ7M52TJ8PHtBMTAztZxH4FJDt3uxjBOe4sR49D59OxCBA225M+4IEZ4l6Fc6EZ/mkihax0XMYxQq6BUP4edOJT0wkbryWGY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
